nixpkgsArchive = "b5aa0fbd538984f6e3d201be0005b4463d8b09f8"

[phases.setup]
nixPkgs = ["dotnetCorePackages.sdk_8_0"]

[phases.build]
cmds = ["dotnet publish -c Release -o out"]

[start]
cmd = "dotnet out/PatientBooking.Api.dll"

[variables]
ASPNETCORE_URLS = "http://0.0.0.0:8080"
